"""
Generate Grafana dashboard with dynamic recommendation detail panels from Azure OpenAI
NO DUMMY DATA - All content pulled from database
"""

import json
import psycopg2
from datetime import datetime

# Database connection
conn = psycopg2.connect(
    host="localhost",
    port=5432,
    database="azure_cost_dev",
    user="postgres",
    password="AzureCost2025!DbPass"
)

cursor = conn.cursor()

# Fetch all recommendations from database
cursor.execute("""
    SELECT 
        id,
        service_name,
        title,
        description,
        recommendation_text,
        potential_savings,
        current_cost,
        savings_percentage,
        priority,
        implementation_effort,
        category,
        status
    FROM ai_recommendations 
    WHERE status = 'pending' AND source = 'azure_openai_real'
    ORDER BY potential_savings DESC
""")

recommendations = cursor.fetchall()

print(f"\n✅ Found {len(recommendations)} real Azure OpenAI recommendations in database")

# Load the base dashboard
with open('config/grafana/dashboards/ai-recommendations-real.json', 'r', encoding='utf-8') as f:
    dashboard = json.load(f)

# Starting Y position for detail panels (after header and table)
y_position = 20
panel_id = 200

# Generate dynamic panels for each recommendation
for rec in recommendations:
    (rec_id, service_name, title, description, recommendation_text, 
     potential_savings, current_cost, savings_percentage, priority, 
     implementation_effort, category, status) = rec
    
    # Priority emoji
    priority_emoji = {
        'high': '🔴',
        'medium': '🟡',
        'low': '🟢'
    }.get(priority.lower(), '⚪')
    
    # Format markdown content from database
    markdown_content = f"""# {priority_emoji} {service_name} - {title}

**💰 Potential Monthly Savings:** ${potential_savings:.2f} ({savings_percentage:.1f}% reduction)

**🎯 Priority:** {priority.upper()} | **⏱️ Effort:** {implementation_effort} | **📊 Category:** {category}

**📈 Service:** {service_name} | **💵 Current Cost:** ${current_cost:.2f}/month

---

## 📋 Description

{description}

---

## 💡 Recommendation

{recommendation_text}

---

## ℹ️ Source

Generated by Azure OpenAI GPT-4 based on real subscription cost data.

**Recommendation ID:** {rec_id} | **Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
    
    # Create panel
    panel = {
        "datasource": {
            "type": "postgres",
            "uid": "PCC52D03280B7034C"
        },
        "gridPos": {
            "h": 18,
            "w": 24,
            "x": 0,
            "y": y_position
        },
        "id": panel_id,
        "options": {
            "code": {
                "language": "plaintext",
                "showLineNumbers": False,
                "showMiniMap": False
            },
            "content": markdown_content,
            "mode": "markdown"
        },
        "pluginVersion": "11.4.0",
        "title": f"{priority_emoji} {service_name} - {title}",
        "type": "text"
    }
    
    dashboard['panels'].append(panel)
    
    y_position += 18
    panel_id += 1
    
    print(f"  ✓ Added panel: {service_name} - ${potential_savings:.2f} savings")

# Save updated dashboard
output_file = 'config/grafana/dashboards/ai-recommendations-real.json'
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(dashboard, f, indent=2, ensure_ascii=False)

cursor.close()
conn.close()

print(f"\n✅ Dashboard generated successfully: {output_file}")
print(f"📊 Total panels: {len(dashboard['panels'])} (5 stat + 1 table + 1 header + {len(recommendations)} recommendations)")
print(f"💰 Total potential savings: ${sum(r[5] for r in recommendations):,.2f}")
print(f"\n🔄 Restart Grafana to see the new dashboard:")
print(f"   docker restart azure-cost-grafana")
